Trivia_API_Testing/Controllers/TriviaController.cs
using Newtonsoft.Json;
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Trivia_API_Testing.Models;
using Trivia_API_Testing.Utilities;
using Trivia_API_Testing.ViewModel;

namespace Trivia_API_Testing.Controllers
{
    public class TriviaController : Controller
    {

        private static TriviaChallengeViewModel triviaQuestionsviewModel =
            new TriviaChallengeViewModel();

        private static CategoryManager categoryManager;
        private static APIJsonParser apiJsonCaller;

        public TriviaController()
        {
            categoryManager = new CategoryManager();
            apiJsonCaller = new APIJsonParser();
        }

        // GET: Trivia
        public ActionResult Index()
        {
            return View();
        }

        //Gets Questions from the API id is optional for category type
        [HttpGet]
        public async Task<ActionResult> GetQuestions(int? id)
        {
            string apiURL = "";
            TriviaQuestionManagerDTO tmpQuestionManagerDTO = 
            new TriviaQuestionManagerDTO();

            if (!id.HasValue)
                apiURL = "https://opentdb.com/api.php?amount=10&type=multiple";
            else
                apiURL = $"https://opentdb.com/api.php?amount=10&category= {id}";

            if (triviaQuestionsviewModel.isSessionFinished || triviaQuestionsviewModel.currentQuestion == 0)
            {
                var jsonData = await apiJsonCaller.GetJsonString(apiURL);
                tmpQuestionManagerDTO = JsonConvert.DeserializeObject<TriviaQuestionManagerDTO>(jsonData);
                triviaQuestionsviewModel.questionsManager = DataMapper.MapTriviaQuestionManager(tmpQuestionManagerDTO);
            }
            return View(triviaQuestionsviewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> GetQuestions(QuestionsFilter questionFilter)
        {
            if (!ModelState.IsValid)
            {
                var vm = new QuestionsFilterViewModel()
                {
                    Catagories = categoryManager
                };
                return View("GetCatagories", vm);
            }
            else
            {
                TriviaQuestionManagerDTO tmpQuestionManagerDTO =
                new TriviaQuestionManagerDTO();

                string apiURL =
                $"https://opentdb.com/api.php?amount={questionFilter.NumOfQuestions}&category={questionFilter.CategoryId}&difficulty={questionFilter.Difficulty}&type={questionFilter.Type}";

                var jsonData = await apiJsonCaller.GetJsonString(apiURL);
                tmpQuestionManagerDTO = JsonConvert.DeserializeObject<TriviaQuestionManagerDTO>(jsonData);
                triviaQuestionsviewModel.questionsManager = DataMapper.MapTriviaQuestionManager(tmpQuestionManagerDTO);

                return View("GetQuestions", triviaQuestionsviewModel);
            }
        }

        //Gets all Questions Categories
        [HttpGet]
        public async Task<ActionResult> GetCatagories()
        {
            triviaQuestionsviewModel.resetViewModel();

            string apiURL = "https://opentdb.com/api_category.php";

            QuestionsFilterViewModel vm = new QuestionsFilterViewModel();

            var jsonData = await apiJsonCaller.GetJsonString(apiURL);
            categoryManager = JsonConvert.DeserializeObject<CategoryManager>(jsonData);

            vm.Catagories = categoryManager;

            return View(vm);
        }

        //Method to grab the users answer form the question
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GetAnswer(string answer)
        {
            if (String.IsNullOrEmpty(answer))
                return View("Index");

            if (answer.Equals(triviaQuestionsviewModel.questionsManager.
            Questions.ElementAt(triviaQuestionsviewModel.currentQuestion).CorrectAnswer))
            {
                triviaQuestionsviewModel.Score += 1;
                Console.WriteLine("Correct");
            }
            else
                Console.WriteLine("False");

            return GetNextQuestion();
        }

        //Moves to the next questions
        [HttpGet]
        public ActionResult GetNextQuestion()
        {
            triviaQuestionsviewModel.currentQuestion++;
            if (triviaQuestionsviewModel.currentQuestion >= 
                triviaQuestionsviewModel.questionsManager.Questions.Count)
                triviaQuestionsviewModel.isSessionFinished = true;

            return  View("GetQuestions",
            triviaQuestionsviewModel);
        }
    }
}

Trivia_API_Testing/Views/Trivia/GetCatagories.cshtml
@model Trivia_API_Testing.ViewModel.QuestionsFilterViewModel
@using Trivia_API_Testing.Models

@{
    ViewBag.Title = "GetCatagories";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



@Html.ValidationSummary(true, "", new { @class = "text-danger" })
<h1>Welcome to Lumin Trivia</h1>
<div class="row">
    @using (Html.BeginForm("GetQuestions", "Trivia"))
    {

    <div class="card">
        <div class="col-lg-12">
            <div class="card-body">

                <div class="form-group">
                    @Html.EditorFor(model => model.QuestionFilter.NumOfQuestions, "Questions amount", new
                    {
                        htmlAttributes = new
                   { @class = "form-control", placeHolder = "Number of questions", min = 1, max = 30 }
                    })
                    @Html.ValidationMessageFor(model => model.QuestionFilter.NumOfQuestions, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    @Html.DropDownListFor(model => model.QuestionFilter.Difficulty,
                    new SelectList(Enum.GetValues(typeof(QuestionDifficulty))), "Select Difficulty", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.QuestionFilter.Difficulty, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.DropDownListFor(model => model.QuestionFilter.Type,
                    new SelectList(Enum.GetValues(typeof(QuestionType))), "Select Type", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.QuestionFilter.Type, "", new { @class = "text-danger" })
                    @Html.ValidationMessageFor(model => model.QuestionFilter.CategoryId, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.DropDownListFor(model => model.QuestionFilter.CategoryId,
                    new SelectList(Model.Catagories.CategoriesList, "CategoryID", "Name"), "Select a Category", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.QuestionFilter.Type, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.AntiForgeryToken()
                    <input type="submit" value="Get Questions" class="btn btn-outline-warning" />
                </div>
            </div>
        </div>
        <br>
    </div>

    }
</div>
<br />
<br />

<hr />


@section scripts{
    @Scripts.Render("~/bundles/jqueryval")
}

<style>
    .card {
        margin-bottom: 20px;
        background-color: darkslategrey;
    }

    h1 {
        color: crimson;
    }
</style>

Trivia_API_Testing/Views/Trivia/GetQuestions.cshtml
@model Trivia_API_Testing.ViewModel.TriviaChallengeViewModel
@using Trivia_API_Testing.Models

@{
    ViewBag.Title = "GetQuestions";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<br />
<br>

<div class="align-content-lg-center">

    @if (!Model.isSessionFinished)
    {
        <div id="bgImage">
            <div class="input-container">
                <p class="text-danger">Difficulty: @Model.questionsManager.Questions.ElementAt(Model.currentQuestion).Difficulty</p>
                <p class="text-warning"> Category: @Model.questionsManager.Questions.ElementAt(Model.currentQuestion).Category</p>
                <h3>@Model.questionsManager.Questions.ElementAt(Model.currentQuestion).Question</h3>

                @using (Html.BeginForm("GetAnswer", "Trivia"))
                {
                    foreach (string possibleAnswer in Model.questionsManager.Questions.ElementAt(Model.currentQuestion).PossibleAnswers)
                    {
                        <label class="btn btn-primary" style="padding:20px 20px">
                            <input type="radio" name="answer" required value="@possibleAnswer" />
                            @possibleAnswer
                        </label>
                        <br />
                    }
                    <br />
                    <br />
                    @Html.AntiForgeryToken()
                    <div class="form-group">
                        <div class="col-12">
                            <input type="submit" value="Next" class="btn btn-info" />
                        </div>
                    </div>
                    <hr />
                }
            </div>
        </div>
    }
    else
    {
        <h4 class="text-success">End of Questions</h4>
        <h3>You have Answered @Model.Score out of @Model.questionsManager.Questions.Count</h3>
        <div>
            @Html.ActionLink("Back", "GetCatagories")
        </div>
    }
</div>


@section scripts{
    @Scripts.Render("~/bundles/jqueryval")
}

<style>
    #bgImage {
        width: 100%;
        background-image: url("https://www.savannahstate.edu/content/mediakitfiles/game-show-lights-stage-stock-small.jpeg");
    }

    .input-container {
        padding: 10px;
        text-align: center;
        color: firebrick;
        font-weight: bolder;
        font-size: xx-large;
    }
</style>

Trivia_API_Testing/Views/Trivia/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>